In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("titanic/train.csv", index_col="PassengerId")
test = pd.read_csv("titanic/test.csv", index_col="PassengerId")

In [3]:
numerical_cols = train.select_dtypes(include="number").columns
categorical_cols = train.select_dtypes(include=["str", "category"]).columns

In [4]:
#Cabin ist etwas nutzlos eigentlich
for df in [train, test]:
    df['Deck'] = df['Cabin'].str[0]
    df['Deck'] = df['Deck'].fillna('0')

In [5]:
#Zu NA Werten. In der Baseline Logistic Regression werde ich es einfach imputen. Datenlecks werden nicht auftreten. Boosting kommt da schon ohne klar

In [6]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
 11  Deck      891 non-null    str
dtypes: float64(2), int64(4), str(6)
memory usage: 83.7 KB

In [7]:
train[(train["Sex"] == "male") & (train["Age"] < 18)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
PassengerId,,,,,,,,,,,,
8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,0
17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,0
51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S,0
60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S,0
64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,0
79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,0
87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S,0
126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C,0
139,0,3,"Osen, Mr. Olaf Elon",male,16.00,0,0,7534,9.2167,NaN,S,0
164,0,3,"Calic, Mr. Jovo",male,17.00,0,0,315093,8.6625,NaN,S,0
165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,0
166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S,0
172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,0
183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,0
184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,F
194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,F
221,1,3,"Sunderland, Mr. Victor Francis",male,16.00,0,0,SOTON/OQ 392089,8.0500,NaN,S,0
262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,0
267,0,3,"Panula, Mr. Ernesti Arvid",male,16.00,4,1,3101295,39.6875,NaN,S,0
279,0,3,"Rice, Master. Eric",male,7.00,4,1,382652,29.1250,NaN,Q,0
283,0,3,"de Pelsmaeker, Mr. Alfons",male,16.00,0,0,345778,9.5000,NaN,S,0
306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,C
334,0,3,"Vander Planke, Mr. Leo Edmondus",male,16.00,2,0,345764,18.0000,NaN,S,0
341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,F
349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,0
353,0,3,"Elias, Mr. Tannous",male,15.00,1,1,2695,7.2292,NaN,C,0
387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,0
408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,0
434,0,3,"Kallio, Mr. Nikolai Erland",male,17.00,0,0,STON/O 2. 3101274,7.1250,NaN,S,0
446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,A
481,0,3,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,NaN,S,0
490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S,0
501,0,3,"Calic, Mr. Petar",male,17.00,0,0,315086,8.6625,NaN,S,0
533,0,3,"Elias, Mr. Joseph Jr",male,17.00,1,1,2690,7.2292,NaN,C,0
550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S,0
551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C,C
575,0,3,"Rush, Mr. Alfred George John",male,16.00,0,0,A/4. 20589,8.0500,NaN,S,0
684,0,3,"Goodwin, Mr. Charles Edward",male,14.00,5,2,CA 2144,46.9000,NaN,S,0
687,0,3,"Panula, Mr. Jaako Arnold",male,14.00,4,1,3101295,39.6875,NaN,S,0
722,0,3,"Jensen, Mr. Svend Lauritz",male,17.00,1,0,350048,7.0542,NaN,S,0
732,0,3,"Hassan, Mr. Houssein G N",male,11.00,0,0,2699,18.7875,NaN,C,0
747,0,3,"Abbott, Mr. Rossmore Edward",male,16.00,1,1,C.A. 2673,20.2500,NaN,S,0
752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,E
756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,0
765,0,3,"Eklund, Mr. Hans Linus",male,16.00,0,0,347074,7.7750,NaN,S,0
788,0,3,"Rice, Master. George Hugh",male,8.00,4,1,382652,29.1250,NaN,Q,0
789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,0
792,0,2,"Gaskell, Mr. Alfred",male,16.00,0,0,239865,26.0000,NaN,S,0
803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,B
804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,0
820,0,3,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,27.9000,NaN,S,0
825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,0
828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,0
832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,0
842,0,2,"Mudd, Mr. Thomas Charles",male,16.00,0,0,S.O./P.P. 3,10.5000,NaN,S,0
845,0,3,"Culumovic, Mr. Jeso",male,17.00,0,0,315090,8.6625,NaN,S,0
851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,0
870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,0

In [8]:
train[train["Name"].str.contains("Master.", na=False)]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
PassengerId,,,,,,,,,,,,
8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S,0
17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q,0
51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S,0
60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S,0
64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S,0
66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C,0
79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S,0
126,1,3,"Nicola-Yarred, Master. Elias",male,12.00,1,0,2651,11.2417,NaN,C,0
160,0,3,"Sage, Master. Thomas Henry",male,NaN,8,2,CA. 2343,69.5500,NaN,S,0
165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S,0
166,1,3,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,20.5250,NaN,S,0
172,0,3,"Rice, Master. Arthur",male,4.00,4,1,382652,29.1250,NaN,Q,0
177,0,3,"Lefebre, Master. Henry Forbes",male,NaN,3,1,4133,25.4667,NaN,S,0
183,0,3,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,31.3875,NaN,S,0
184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,F
194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,F
262,1,3,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,31.3875,NaN,S,0
279,0,3,"Rice, Master. Eric",male,7.00,4,1,382652,29.1250,NaN,Q,0
306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,C
341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,F
349,1,3,"Coutts, Master. William Loch ""William""",male,3.00,1,1,C.A. 37671,15.9000,NaN,S,0
387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S,0
408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S,0
446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,A
481,0,3,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,46.9000,NaN,S,0
490,1,3,"Coutts, Master. Eden Leslie ""Neville""",male,9.00,1,1,C.A. 37671,15.9000,NaN,S,0
550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S,0
710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,15.2458,NaN,C,0
752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,E
756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S,0
788,0,3,"Rice, Master. George Hugh",male,8.00,4,1,382652,29.1250,NaN,Q,0
789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S,0
803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,B
804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C,0
820,0,3,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,27.9000,NaN,S,0
825,0,3,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,39.6875,NaN,S,0
828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C,0
832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,0
851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S,0
870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,0

In [9]:
#Titel
for df in [train, test]:
    df['Title'] = df['Name'].str.extract(r',\s*([^\.]+)\.')
    keep = ['Mr', 'Mrs', 'Miss', 'Master', 'Dr']
    df['Title'] = df['Title'].where(df['Title'].isin(keep), other='Rare')

    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1  # +1 für die Person selbst
    df['IsAlone'] = (df['FamilySize'] == 1).astype(int)

In [10]:
def family_category(size):
    if size == 1:
        return 'Alone'
    elif size <= 4:
        return 'Small'
    else:
        return 'Large'
for df in [train, test]:
    df['FamilyCategory'] = df['FamilySize'].apply(family_category)

In [11]:
train.groupby('FamilySize')['Survived'].agg(['mean', 'count'])

                mean  count
FamilySize
1           0.303538    537
2           0.552795    161
3           0.578431    102
4           0.724138     29
5           0.200000     15
6           0.136364     22
7           0.333333     12
8           0.000000      6
11          0.000000      7

In [12]:
train['Title'].value_counts()

Title
Mr        517
Miss      182
Mrs       125
Master     40
Rare       20
Dr          7
Name: count, dtype: int64

In [13]:
for df in [train, test]:
    df["Embarked"] = df["Embarked"].fillna("S")

    df["Log_Fare"] = np.log1p(df["Fare"])

In [14]:
#Geschätzte Age-Werte: Ich nehme an, die Schätzungen sind korrekt
for df in [train, test]:
    df['Age'] = df.groupby('Title')['Age'].transform(
        lambda x: x.fillna(x.median())
    )
    #Kind-Flag
    df['IsChild'] = (df['Age'].dropna() < 18).astype(int)

train.Age = np.floor(train.Age).astype("Int64")
test.Age = np.floor(test.Age).astype("Int64")

In [15]:
combined_tickets = pd.concat([train['Ticket'], test['Ticket']])
ticket_counts_combined = combined_tickets.value_counts()

train['TicketFrequency'] = train['Ticket'].map(ticket_counts_combined)
test['TicketFrequency'] = test['Ticket'].map(ticket_counts_combined)

In [16]:
train = train.drop(columns=["Parch", "SibSp", "Name", "Cabin", "Ticket"])
test = test.drop(columns=["Parch", "SibSp", "Name", "Cabin", "Ticket"])

In [18]:
train.Deck.value_counts()

Deck
0    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [17]:
train.to_csv("train.csv", index=True)
test.to_csv("test.csv", index=True)